### ISSUE TITLE
Finish admin dashboard

### ISSUE THREAD

**Issue by quick007** [JsServices/JSBoard#2]
# JSBoard - Feature request

## Checklist

- [x] You have read and agree to the Readme
- [x] You have searched the issue tracker to make sure this is not a duplicate suggestion

### Frontend

- [ ] Revamp top & side nav
- [ ] Create a wrapper to standardize all the pages
- [ ] Make a new bottom nav
- [ ] Create default error, loading, and saved screens
---
- [ ] Homepage
- [ ] Main settings
- [ ] Modueles (plugins)
- [ ] Themes
- [ ] Custom pages
---
- [ ] Forum global settings
- [ ] Catagories
- [ ] Labels
- [ ] Stats
---
- [ ] Users
- [ ] Roles
- [ ] Reports
- [ ] Punishments
---
- [ ] Add formik and markdown editors to all the pages

### Backend

- [ ] Use socketio to send the info to fill into the boxes (fill in the formik default values) 

---
**Write to mongo:**

- [ ] Homepage
- [ ] Main settings
- [ ] Modueles (plugins)
- [ ] Themes
- [ ] Custom pages
---
- [ ] Forum global settings
- [ ] Catagories
- [ ] Labels
- [ ] Stats
---
- [ ] Users
- [ ] Roles
- [ ] Reports
- [ ] Punishments

## Any extra notes

I really don't wanna do mongo for all of these too

**Comment by Bloxs** [comment]
> Stale issue message

@quick007 You forgot to configure the bot?

**Comment by quick007** [comment]
I probably should just remove it
